language: android

android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - tools

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  #- touch ~/.android/repositories.cfg
  - sdkmanager --list || true
  - sdkmanager tools >/dev/null
  - sdkmanager "platforms;android-27" >/dev/null

jdk:
  - oraclejdk8

sudo: required
dist: trusty
group: stable

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - cd plugin; ./gradlew check
  - $TRAVIS_BUILD_DIR/tests/app/functionalTestStubbed.sh
